### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Harshdev625**
Updated ReadMe added How to find the midpoint of Linked List.

### CODE REVIEW

**Comment by Harshdev625** [comment]
okay ma'am I have made the changes.

**Comment by Sapna127** [comment]
You need yo add the algorithm as well

**Comment by Harshdev625** [comment]
Ma'am, I Updated Algorithm Two Pointers, and also I have done a few more pull requests kindly go through them.

**Comment by Harshdev625** [comment]
Please Merge it.

**Pull request closed without merging**
